name: Main workflow

on:
  pull_request:
  push:

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        swift-version:
          - 2.2
          - 3.1
          - 4.2
          - 5.3

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test Plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: swift --version
          version: ${{ matrix.swift-version }}
