name: Main workflow

on:
  pull_request:
  push:

jobs:
  plugin-test-ubuntu:
    strategy:
      matrix:
        container:
          - ubuntu:18.04
        swift-version:
          - 3.1
          - 4.2.1
          - 5.3.2

    env:
      DEBIAN_FRONTEND: noninteractive

    container:
      image: ${{ matrix.container }}

    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: apt-get update && apt-get install -y 
          binutils 
          cmake 
          curl 
          git 
          gnupg2 
          libc6-dev 
          libcurl4 
          libedit2 
          libgcc-5-dev 
          libpython2.7 
          libsqlite3-0 
          libstdc++-5-dev 
          libxml2 
          lsb-release 
          ninja-build 
          pkg-config 
          tzdata 
          zlib1g-dev

      - name: Test Plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: swift --version
          version: ${{ matrix.swift-version }}

  plugin-test-macos:
    strategy:
      matrix:
        os:
          - macos-latest
        swift-version:
          - 2.2.1
          - 3.4.1
          - 4.2.1
          - 5.3.2

    runs-on: ${{ matrix.os }}

    steps:
      - name: Test Plugin
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: swift --version
          version: ${{ matrix.swift-version }}
